### PR TITLE
Option for ContextDiagram with only Entity Names (properties and methods removed) and Option to ignore spamming Entities 

### PR DESCRIPTION
**Pull request by DigitalVisionMax**
~ Option for ContextDiagram with only Entity Names (properties and methods removed) 
~ Option to deClutter by ignore spamming Entities  and entities name starting with UI (UIKit and other classes by Apple)
~ Added a Configs javascript file for the user options. WIP. Need help from JavaScript experts in externalizing these config entries.

### CODE REVIEW

**Comment by DigitalVisionMax** [comment]
image

**Comment by gagoyal** [comment]
This is a great way to deClutter and display only the essential info about classes and hierarchy. I think I should try this in my forked uml generator repository (https://github.com/gagoyal/swiftuml). Or even better, make it configurable sometime in future.

**Comment by DigitalVisionMax** [comment]
~ Entity and Relationship deletion enabled 
~ Animated integration with Entity node and relationship edges 
~ Entity Name and Type are added as hover over text (Node Title)
~ To get the High-level Context Diagram only with entity Names properties and methods removed , set isContextDiagram to true in htmltemplate/js/entity.js
~ To deClutter the diagram by avoiding the obvious entities,  update the ignoreEntities in htmltemplate/js/diagram.js
["String", "Int", "Double", "Float", "Bool", "CGPoint", "CGSize","NSObject", "AnyObject", "Error", "Date","class","Codable", "DeCodable", "Encodable", "Equatable","CodingKeys"]

**Review by ZdravkoN — APPROVED** [review]

**Comment by yoshimkd** [comment]
Thank you very much for the improvements @DigitalVisionMax!

**Pull request merged**
